name: valify
description: Validating your inputs like never before with highly intuitive constraint classes
version: 0.0.1
author: m_zaink
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.3

dev_dependencies:
  test: ^1.15.4
  pedantic: ^1.9.0